/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.coreui;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f030027;
        public static final int coordinatorLayoutStyle = 0x7f0300ab;
        public static final int font = 0x7f0300e2;
        public static final int fontProviderAuthority = 0x7f0300e4;
        public static final int fontProviderCerts = 0x7f0300e5;
        public static final int fontProviderFetchStrategy = 0x7f0300e6;
        public static final int fontProviderFetchTimeout = 0x7f0300e7;
        public static final int fontProviderPackage = 0x7f0300e8;
        public static final int fontProviderQuery = 0x7f0300e9;
        public static final int fontStyle = 0x7f0300ea;
        public static final int fontVariationSettings = 0x7f0300eb;
        public static final int fontWeight = 0x7f0300ec;
        public static final int keylines = 0x7f030124;
        public static final int layout_anchor = 0x7f030129;
        public static final int layout_anchorGravity = 0x7f03012a;
        public static final int layout_behavior = 0x7f03012b;
        public static final int layout_dodgeInsetEdges = 0x7f030157;
        public static final int layout_insetEdge = 0x7f030160;
        public static final int layout_keyline = 0x7f030161;
        public static final int statusBarBackground = 0x7f03028e;
        public static final int ttcIndex = 0x7f030327;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f050080;
        public static final int notification_icon_bg_color = 0x7f050081;
        public static final int ripple_material_light = 0x7f05008b;
        public static final int secondary_text_default_material_light = 0x7f05008d;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f06004f;
        public static final int compat